name: Build and Release mdBook (Multi-Platform 中文搜索版)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]   # 这里要哪些平台就列哪些

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build mdBook
        run: cargo build --release

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: auto-build
          name: "Auto Build Release"
          files: |
            target/release/mdbook.exe
            target/release/mdbook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
